### ISSUE TITLE
Forgot password Flow

### ISSUE THREAD

**Issue by misha130** [codidact/authentication#13]
**Is your feature request related to a problem? Please describe.**
From the Login Page there should be an option for forgot password.

**Describe the solution you'd like**
Similar to Login - https://github.com/luap42/codidact-design-draft/blob/master/login.html
Only with Email only.

**Comment by cellio** [comment]
Is the idea that clicking "forgot password" sends a reset link to the registered email address?

**Comment by misha130** [comment]
Yes that is the idea

**Comment by Daksh14** [comment]
Closed with https://github.com/codidact/authentication/pull/19
