### ISSUE TITLE
Create an email service.

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#18]
When the user forgets his password, an email would have to be send with a link to reset the password. 

The password would not be send in plain text, but some token that can be used to set a new password.

**Comment by cellio** [comment]
See additional context in comments on https://github.com/codidact/authentication/pull/17.

**Comment by misha130** [comment]
Please outline how do you plan to create the HTML output for the emails.
RazorEngine? Plain HTML with replace of texts inside of it?

**Comment by cellio** [comment]
> Please outline how do you plan to create the HTML output for the emails.
> RazorEngine? Plain HTML with replace of texts inside of it?

Does email need to be HTML?  A raw URL will render as a link in HTML-capable clients (which is most of them), and we don't need our email to be fancy or pretty.  What bad things happen if we just send text?

(While I personally prefer plain text for my own email, that's *not* why I'm asking.  I'm asking because it sounds from this comment like there are some additional complexities with HTML, so it's fair to ask if we need them.)

**Comment by misha130** [comment]
> Does email need to be HTML?
I guess not, just used to it being HTML I never even questioned the fact.

> What bad things happen if we just send text?
I am pretty sure you can put a logo on top if need be and its easier to read.
There aren't any bad things.

The complexity though is more a feature. Having a one layout/format for all our emails and having an engine create the HTML with the needed content injected.

**Comment by cellio** [comment]
Sounds like complexity that could wait?  I mean, if it's easy and you want to do it then sure, but I wouldn't call *pretty* email MVP.  If there's something more critical that you would otherwise be working on, this aspect of email could wait.

**Comment by asynts** [comment]
> Please outline how do you plan to create the HTML output for the emails.
RazorEngine? Plain HTML with replace of texts inside of it?

Let's do one thing at a time. Razor sounds like a good idea though.

**Comment by Daksh14** [comment]
We would need to design a template that will be common to most of the emails we will send, like verification emails, forgot password emails and other announcements. Razor indeed sounds like a good idea. I'll ask the frontend + docs team to design a template
