### ISSUE TITLE
Unblock the project for the frontend to step in.

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#22]
The following things have to happen:

  - [x] Implement the `ICoreApiService` interface such that users can be created in the core instance.

  - [ ] Create a script for Windows and Linux that sets up the environment.

  - [ ] Scaffold the entities.

  - [ ] Prepare configuration files to host an instance.

  - [ ] More things that I have not thought of.

The idea is to do this quickly and then do it properly after the frontend is unblocked.

*Addendum.*

  - [ ] Figure out what to do with request that are not dealing with a community. Currently, we have nothing to do this because each core instance represents one community.

**Comment by misha130** [comment]
- [ ] Put Integration tests for Login, Reset Password, Register

**Comment by asynts** [comment]
I am claiming the "Prepare configuration files to host an instance." task. I am planing to complete this ~~today~~ ~~tomorrow~~ some time in the future.
