### ISSUE TITLE
Figure out how the Return URL works.

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#4]
In some places it is called the 'ReturnUrl' in other places 'RedirectUri,' I must admit that I have no idea what exactly is going on.

Identity Server seems to interact with the 'returnurl' parameter which is passed to the login page. My understanding is that it redirects a user after a successful login to this URL (or URI?) and includes an authorization code in the fragment part of the URL (or URI?).

This URL seems to be validated against the `Clients:X:RedirectUris` configuration option, which is `IdentityServer:Clients:0:RedirectUris` for us.

This behavior should be verified with a tool like Wireshark and some research in general.

**Comment by misha130** [comment]
RedirectURL is different than ReturnURL by the fact that each of them can be configured differently and also one of them is part of the passed token and one of them is in the query.
I might be wrong but redirect is the allowed host to go back to and return is the actual path to which to return to upon success

**Comment by asynts** [comment]
This is my main point:

  > This behavior should be verified with a tool like Wireshark and some research in general.

We should be certain that it works correctly, but I just want #2 to get ready to merge because it is blocking everything else.

**Comment by asynts** [comment]
To elaborate what is unclear:

If you go to the client and press 'login' it will redirect you to `http://localhost:5001/account/login` with the following parameter for 'ReturnUrl':

`%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dcodidact_client%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5000%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%26code_challenge%3DrisP9BK-oE2wU_rGMjw7CHc5zRxCyH64t3AUmDqR06E%26code_challenge_method%3DS256%26response_mode%3Dform_post%26nonce%3D637183220914695443.NjM4NGU2ZjAtMTFjNy00NjBjLTkyZjYtZDE3NWQ2NmY4NmNlYmJmY2QxMGUtN2U1MC00OTk5LTg0ZjgtY2I3M2Y2ZmFkOTU4%26state%3DCfDJ8N1rlLQcUn5EowPqv5DxVkC7_ttZUmmrUI8FNYYoHzjqZBtWzD5IT8OuEY3nQTODGVqzSwl9bTSLlG0bqTCnQznbRCaAZZBfPw7TIBkam_UW2oqrcIME_SJQ7YyVtwZzbzNXhul_whXHPVpjLGARJHPmEjdKPyx5uTObVUBTXaIqwbC_-gmIqdxqM-Y1o-jHZgP-fkNvqOWKty8FCaV8uW2Yx9TEjGt7EvPzK_ijoPjeoI_QwH2E6TX1DlIhOnQwqNYE3iGWEBZvsqVqzzSEzfttoYQsib1e-k3717qfV1CWOoAXPg4lDBmQ4GEhpcFScr-225XZ36Pe-J37TAupKroNFKCl5Odspu-dPPH59fR488JPlhjDjEzi_1kdNzjcxw%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D5.5.0.0`

Which after URL decoding looks like this:

`/connect/authorize/callback?client_id=codidact_client&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fsignin-oidc&response_type=code&scope=openid%20profile&code_challenge=risP9BK-oE2wU_rGMjw7CHc5zRxCyH64t3AUmDqR06E&code_challenge_method=S256&response_mode=form_post&nonce=637183220914695443.NjM4NGU2ZjAtMTFjNy00NjBjLTkyZjYtZDE3NWQ2NmY4NmNlYmJmY2QxMGUtN2U1MC00OTk5LTg0ZjgtY2I3M2Y2ZmFkOTU4&state=CfDJ8N1rlLQcUn5EowPqv5DxVkC7_ttZUmmrUI8FNYYoHzjqZBtWzD5IT8OuEY3nQTODGVqzSwl9bTSLlG0bqTCnQznbRCaAZZBfPw7TIBkam_UW2oqrcIME_SJQ7YyVtwZzbzNXhul_whXHPVpjLGARJHPmEjdKPyx5uTObVUBTXaIqwbC_-gmIqdxqM-Y1o-jHZgP-fkNvqOWKty8FCaV8uW2Yx9TEjGt7EvPzK_ijoPjeoI_QwH2E6TX1DlIhOnQwqNYE3iGWEBZvsqVqzzSEzfttoYQsib1e-k3717qfV1CWOoAXPg4lDBmQ4GEhpcFScr-225XZ36Pe-J37TAupKroNFKCl5Odspu-dPPH59fR488JPlhjDjEzi_1kdNzjcxw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0`

So apparently it redirects to `http://localhost:5001/connect/authorize/callback` and then to `http://localhost:5000/signin-oidc`. Clearly, something magical is happening here, that I can not comprehend.

This issue is essentially that someone (likely me because I wrote the code) has to go and read all of these RFC papers and figure out exactly what is going on and why.

**Comment by misha130** [comment]
I think its easier to think of this in terms of OAuth2 and not in terms of OpenID.
When you do this normally with code authentication the following happens:

[
![image](https://user-images.githubusercontent.com/6649900/75494832-17a16200-598b-11ea-9388-6d69ededcb23.png)
](url)

So this callback url refers to stage 3. Which after OpenID asks the token end point for the token, sets it to the cookie and redirects to the proper URL..

In my previous comment I was mistakenly refering to PostLogoutRedirectUri which unlike the login is mostly unknown to the identityserver unless specified. It may require testing whether after a logout the project redirects properly
