### ISSUE TITLE
Do we have a CSRF Vulnerbility on the Logout Page?

### ISSUE THREAD

**Issue by asynts** [codidact/authentication#5]
*Note. This issue refers to #2.*

I have already brought this up before but never precisely tested it, instead I looked at the code and tried to reason about it that way.

https://github.com/codidact/core/pull/62#discussion_r379824298

This should be tested properly.

**Comment by misha130** [comment]
The question is whether the logout action in the auth project is always a POST?

**Comment by asynts** [comment]
The question is essentially if the cookies are deleted before or after the logout on the authentication server. (That is from the clients perspective.) If it is the former, it would be possible to delete the cookies from Java Script without any user explicitly doing it.

It is a bit difficult to tell where the logout stuff actually happens because of the dependency injection stuff.

My understanding is that the authentication schemas are added here:

https://github.com/asynts/codidact-authentication/blob/a681d71a9ab433176908e5b53531ecbc6b2313d8/src/Client/Startup.cs#L53-L54

And when the user visits `/logout` (with a GET request!) one calls callbacks on each authentication handler:

https://github.com/asynts/codidact-authentication/blob/a681d71a9ab433176908e5b53531ecbc6b2313d8/src/Client/Pages/Logout.cshtml.cs#L12

The 'oidc' should be fine because it essentially redirects to the authentication server and requires a post request there. The 'cookie' schema is what I am concerned about, are the cookies deleted immediately or does the 'AddOpenIdConnect' stuff mess with that?

This is not a huge priority but I thought I would create an issue about it before it is forgotten.

**Comment by asynts** [comment]
Moved to codidact/core#67.
